/**
 * Hacker Text Effect
 */

const mumaker = require('mumaker');
const config = require('../../config');

module.exports = {
  name: 'hacker',
  aliases: [],
  category: 'textmaker',
  description: 'Create hacker text effect',
  usage: '.hacker <text>',
  
  async execute(sock, msg, args) {
    try {
      const text = args.join(' ');
      const chatId = msg.key.remoteJid;
      
      if (!text) {
        return await sock.sendMessage(chatId, { 
          text: '❌ Please provide text\nExample: .hacker BFF' 
        }, { quoted: msg });
      }
      
      // Good modern hacker/matrix style
      const result = await mumaker.ephoto('https://en.ephoto360.com/create-a-hacker-anonymous-text-effect-712.html', text);
      
      await sock.sendMessage(chatId, {
        image: { url: result.image },
        caption: `🕶️ GENERATED BY ${config.botName || 'KnightBot-Mini'}`
      }, { quoted: msg });
      
    } catch (error) {
      console.error('Error in hacker command:', error);
      await sock.sendMessage(msg.key.remoteJid, { 
        text: `❌ Hacker effect failed: ${error.message || 'API error'}\nTry .hacker again` 
      }, { quoted: msg });
    }
  }
};
