/**
 * Arena Text Effect
 */

const mumaker = require('mumaker');
const config = require('../../config');

module.exports = {
  name: 'arena',
  aliases: [],
  category: 'textmaker',
  description: 'Create bold arena text effect',
  usage: '.arena <text>',
  
  async execute(sock, msg, args) {
    try {
      const text = args.join(' ');
      const chatId = msg.key.remoteJid;
      
      if (!text) {
        return await sock.sendMessage(chatId, { 
          text: '❌ Please provide text\nExample: .arena Marvin' 
        }, { quoted: msg });
      }
      
      // Better bold arena / gaming style
      const result = await mumaker.ephoto('https://en.ephoto360.com/create-cover-arena-of-valor-by-mastering-360.html', text);
      
      await sock.sendMessage(chatId, {
        image: { url: result.image },
        caption: `🔥 GENERATED BY ${config.botName || 'KnightBot-Mini'}`
      }, { quoted: msg });
      
    } catch (error) {
      console.error('Error in arena command:', error);
      await sock.sendMessage(msg.key.remoteJid, { 
        text: `❌ Arena effect failed. Try again.` 
      }, { quoted: msg });
    }
  }
};
