/**
 * Metallic Text Effect
 */

const mumaker = require('mumaker');
const config = require('../../config');

module.exports = {
  name: 'metallic',
  aliases: [],
  category: 'textmaker',
  description: 'Create metallic text effect',
  usage: '.metallic <text>',
  
  async execute(sock, msg, args, context) {
    const { from, reply } = context;
    try {
      const text = args.join(' ');
      if (!text) {
        return reply('Please provide text to generate\nExample: .metallic Nick');
      }
      
      const result = await mumaker.ephoto('https://en.ephoto360.com/impressive-decorative-3d-metal-text-effect-798.html', text);
      
      if (!result || !result.image) {
        throw new Error('No image URL received from the API');
      }
      
      await sock.sendMessage(from, {
        image: { url: result.image },
        caption: `GENERATED BY ${config.botName}`
      }, { quoted: msg });
      
    } catch (error) {
      console.error('Error in metallic command:', error);
      reply(`Error: ${error.message}`);
    }
  }
};
