const mumaker = require('mumaker');
const config = require('../../config');

module.exports = {
    name: 'purple',
    aliases: [],
    category: 'textmaker',
    description: 'Create purple text effect',
    usage: '.purple <text>',

    async execute(sock, msg, args, context) {
        const { from, reply } = context;
        const text = args.join(' ');
        if (!text) return reply('❌ Example: .purple Cohenz Pro');

        try {
            // This calls the real API
            const result = await mumaker.ephoto('https://example.com/purple', text);
            // result = { image: 'url' }
            await sock.sendMessage(from, {
                image: { url: result.image },
                caption: `GENERATED BY ${config.botName}`
            }, { quoted: msg });
        } catch (error) {
            console.error('Error in purple:', error);
            reply(`❌ ${error.message}`);
        }
    }
};
