/**
 * Text Effect Command
 */

const mumaker = require('mumaker');
const config = require('../../config');

module.exports = {
  name: 'sand',                    // ← Change this for each file
  aliases: [],
  category: 'textmaker',
  description: 'Create arena text effect',
  usage: '.sand <text>',
  
  async execute(sock, msg, args) {
    try {
      const text = args.join(' ').trim();
      const chatId = msg.key.remoteJid;
      
      if (!text) {
        return await sock.sendMessage(chatId, { 
          text: '❌ Please provide text!\nExample: .arena BFF' 
        }, { quoted: msg });
      }

      // ←←← Change ONLY this URL for each command ↓↓↓
      const ephotoUrl = 'https://en.ephoto360.com/create-cover-arena-of-valor-by-mastering-360.html';

      const result = await mumaker.ephoto(ephotoUrl, text);

      if (!result || !result.image) {
        throw new Error('Failed to get image from API');
      }

      await sock.sendMessage(chatId, {
        image: { url: result.image },
        caption: `GENERATED BY ${config.botName || 'KnightBot-Mini'}`
      }, { quoted: msg });

    } catch (error) {
      console.error(`Error in ${module.exports.name} command:`, error);
      await sock.sendMessage(msg.key.remoteJid, { 
        text: `❌ Failed to generate ${module.exports.name} effect.\nTry again later or check API status.` 
      }, { quoted: msg });
    }
  }
};
