/**
 * Sand Text Effect
 */

const mumaker = require('mumaker');
const config = require('../../config');

module.exports = {
  name: 'sand',
  aliases: [],
  category: 'textmaker',
  description: 'Create sand text effect',
  usage: '.sand <text>',

  async execute(sock, msg, args, context) {
    const { from, reply } = context;
    try {
      const text = args.join(' ');
      if (!text) {
        return reply('Please provide text to generate\nExample: .sand Nick');
      }
      
      const result = await mumaker.ephoto('https://en.ephoto360.com/write-names-and-messages-on-the-sand-online-582.html', text);
      
      if (!result || !result.image) {
        throw new Error('No image URL received from the API');
      }
      
      await sock.sendMessage(from, {
        image: { url: result.image },
        caption: `GENERATED BY ${config.botName}`
      }, { quoted: msg });
      
    } catch (error) {
      console.error('Error in sand command:', error);
      reply(`Error: ${error.message}`);
    }
  }
};
